[package]
name = "gigi-downloading"
version.workspace = true
edition = "2021"

[dependencies]
libp2p = { workspace = true, features = ["plaintext"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
crossterm = { workspace = true }
indicatif = { workspace = true }
console = { workspace = true }
tokio-util = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
async-trait = "0.1"