[package]
name = "gigi-p2p"
version = "0.0.1"
edition = "2021"

[dependencies]
gigi-dns = { path = "../gigi-dns" }
gigi-file-sharing = { path = "../gigi-file-sharing" }
gigi-store = { path = "../gigi-store" }
libp2p = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
thiserror = { workspace = true }
bytes = { workspace = true }
blake3 = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
mime_guess = "2.0"
url = "2"
sea-orm = "1.1.19"

[dev-dependencies]
tracing-subscriber = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
indicatif = { workspace = true }
console = { workspace = true }
chrono = { workspace = true }
tempfile = "3"
sea-orm = "1.1.19"

[[example]]
name = "chat"