[package]
name = "gigi-gossip"
version = "0.1.0"
edition = "2021"

[dependencies]
gigi-mdns = { path = "../gigi-mdns" }
libp2p = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
humantime = { workspace = true }

[features]
default = []
examples = ["dep:tracing-subscriber", "dep:clap"]

[[example]]
name = "chat"
required-features = ["examples"]