[default]
description = "Default permissions for the plugin"
permissions = [
  # Peer commands
  "allow-get-peer-id",
  "allow-try-get-peer-id",
  # Config commands
  "allow-messaging-get-peers",
  "allow-messaging-set-nickname",
  "allow-messaging-get-public-key",
  "allow-messaging-get-active-downloads",
  "allow-messaging-update-config",
  "allow-messaging-get-config",
  # Messaging commands
  "allow-messaging-initialize-with-key",
  "allow-messaging-send-message",
  "allow-messaging-send-message-to-nickname",
  "allow-messaging-send-direct-share-group-message",
  "allow-messaging-join-group",
  "allow-messaging-send-group-message",
  "allow-emit-current-state",
  "allow-messaging-get-message-history",
  "allow-messaging-save-shared-files",
  "allow-get-messages",
  "allow-search-messages",
  "allow-clear-messages-with-thumbnails",
  "allow-get-file-thumbnail",
  "allow-get-full-image-by-path",
  "allow-get-full-image",
  # File commands
  "allow-messaging-send-file-message-with-path",
  "allow-messaging-send-group-file-message-with-path",
  "allow-messaging-share-file",
  "allow-messaging-request-file",
  "allow-messaging-request-file-from-nickname",
  "allow-messaging-cancel-download",
  "allow-messaging-get-shared-files",
  "allow-messaging-remove-shared-file",
  "allow-messaging-get-image-data",
  "allow-messaging-get-file-info",
  "allow-messaging-select-any-file",
  "allow-messaging-share-content-uri",
  # Utils commands
  "allow-clear-app-data",
  # Conversation commands
  "allow-get-conversations",
  "allow-get-conversation",
  "allow-upsert-conversation",
  "allow-update-conversation-last-message",
  "allow-increment-conversation-unread",
  "allow-mark-conversation-as-read",
  "allow-delete-conversation",
  # Auth commands
  "allow-auth-check-account",
  "allow-auth-signup",
  "allow-auth-login",
  "allow-auth-get-account-info",
  "allow-auth-delete-account",
  "allow-auth-verify-password",
  # Group commands
  "allow-group-create",
  "allow-group-join",
  "allow-group-get-all",
  "allow-group-get",
  "allow-group-delete",
  "allow-group-update",
]
