[workspace]
resolver = "2"
members = [
  "apps/gigi-app/src-tauri",
  "apps/gigi-mobile/src-tauri",
  "pkgs/gigi-messaging",
  "pkgs/mdns-nickname",
  "pkgs/gigi-downloading",
]

[workspace.package]
version = "0.0.1"

[workspace.dependencies]
tauri = { version = "2.6.2", features = ["test"] }
serde = "1.0"
thiserror = "2"
tokio = { version = "1.37.0", features = ["full"] }
libp2p = { version = "0.56.0", features = [
  "macros",
  "gossipsub",
  "mdns",
  "tokio",
  "noise",
  "yamux",
  "tcp",
  "quic",
  "request-response",
] }
serde_json = "1.0"
gigi-messaging = { version = "0.0.1", path = "./pkgs/gigi-messaging" }
mdns-nickname = { version = "0.0.1", path = "./pkgs/mdns-nickname" }
gigi-downloading = { version = "0.0.1", path = "./pkgs/gigi-downloading" }


[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
