[package]
name = "direct-messaging"
version.workspace = true
edition = "2021"

[dependencies]
libp2p.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
anyhow.workspace = true
uuid.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
base64 = "0.21"
mime = "0.3"
mime_guess = "2.0"
async-trait = "0.1"
serde_bytes = "0.11"

[dev-dependencies]
tokio.workspace = true