[package]
name = "gigi-messaging"
edition = "2024"
version.workspace = true

[dependencies]
gigi-p2p.workspace = true
tauri.workspace = true
thiserror.workspace = true
tokio.workspace = true
serde = { version = "1.0", features = ["derive"] }
