[package]
name = "gigi-messaging"
version = "0.0.1"
edition = "2021"

[lib]
name = "gigi_messaging_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = []
tauri = ["dep:tauri"]



[dependencies]
gigi-p2p.workspace = true
tokio.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
base64.workspace = true
dirs = "6.0"
uuid.workspace = true
futures.workspace = true
libp2p.workspace = true
anyhow.workspace = true
tracing-subscriber = "0.3"

[dependencies.tauri]
workspace = true
optional = true
features = ["test"]