[package]
name = "gigi-messaging"
edition = "2024"
version.workspace = true

[dependencies]
hex = "0.4.3"
libp2p.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
thiserror.workspace = true
tokio.workspace = true
