[package]
name = "mdns-nickname"
version.workspace = true
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
rand = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
futures = "0.3"
async-trait = "0.1"